name = "e-commerce"
author = "prithunarang"

[[services]]
internal_port = 3000
command = "npm start"
env = {
  "MONGODB_URI" = "mongodb+srv://prithunarang:Krsna108@e-commerce.ls62ryh.mongodb.net",
  "SESSION_SECRET" = "Our little secret"
}

[[services.envs]]
name = "MONGODB_URI"
generator = "mongodb-atlas"

[[services.envs]]
name = "SESSION_SECRET"
generator = "secret"

[[databases]]
name = "mongodb-uri"
type = "mongodb"
version = "4.4"